apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"api-operator","namespace":"apim-demo"},"spec":{"replicas":1,"selector":{"matchLabels":{"name":"api-operator"}},"template":{"metadata":{"labels":{"name":"api-operator"}},"spec":{"containers":[{"command":["api-operator"],"env":[{"name":"WATCH_NAMESPACE","value":""},{"name":"WATCH_CLUSTER_LEVEL","value":"false"},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"OPERATOR_NAME","value":"api-operator"},{"name":"SYSTEM_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"image":"wso2/k8s-api-operator:2.0.0","imagePullPolicy":"Always","name":"api-operator","ports":[{"containerPort":9445}],"resources":{"limits":{"cpu":"500m","memory":"500Mi"},"requests":{"cpu":"250m","memory":"250Mi"}}}],"serviceAccountName":"api-operator"}}}}
  creationTimestamp: "2021-06-03T05:39:57Z"
  generation: 3
  name: api-operator
  namespace: apim-demo
  resourceVersion: "65798050"
  uid: 80bbc091-35b6-4d79-b3d6-b4630f681434
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: api-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: api-operator
    spec:
      containers:
      - command:
        - api-operator
        env:
        - name: WATCH_NAMESPACE
        - name: WATCH_CLUSTER_LEVEL
          value: "false"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: api-operator
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: wso2/k8s-api-operator:2.0.0
        imagePullPolicy: Always
        name: api-operator
        ports:
        - containerPort: 9445
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 250Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: api-operator
      serviceAccountName: api-operator
      terminationGracePeriodSeconds: 30

