apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"name":"api-operator"},"name":"operator-service","namespace":"apim-demo"},"spec":{"ports":[{"name":"https-operator","nodePort":30445,"port":9445,"protocol":"TCP","targetPort":9445}],"selector":{"name":"api-operator"},"type":"NodePort"}}
  creationTimestamp: "2021-06-03T04:46:42Z"
  labels:
    name: api-operator
  name: operator-service
  namespace: apim-demo
  resourceVersion: "1649224"
  uid: 4c7f2420-886a-4125-bd1c-176deb808f60
spec:
  clusterIP: 10.8.0.202
  clusterIPs:
  - 10.8.0.202
  externalTrafficPolicy: Cluster
  ports:
  - name: https-operator
    nodePort: 30445
    port: 9445
    protocol: TCP
    targetPort: 9445
  selector:
    name: api-operator
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
