apiVersion: v1
data:
  deployment.toml: |-
    [server]
    hostname = "am.wso2.com"
    #offset=0
    base_path = "${carbon.protocol}://${carbon.host}:${carbon.management.port}"
    #discard_empty_caches = false
    server_role = "default"

    [tenant_mgt]
    enable_email_domain= true

    [super_admin]
    username = "admin@gogo.com"
    password = "admin"
    create_admin_account = true

    [user_store]
    type = "database_unique_id"

    [database.apim_db]
    type = "mysql"
    url = "jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_DB?  useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
    username = "wso2carbon"
    password = "wso2carbon"
    driver = "com.mysql.cj.jdbc.Driver"

    [database.shared_db]
    type = "mysql"
    url = "jdbc:mysql://wso2am-mysql-db-service:3306/WSO2AM_SHARED_DB?    useSSL=false&amp;autoReconnect=true&amp;requireSSL=false&amp;verifyServerCertificate=false"
    username = "wso2carbon"
    password = "wso2carbon"
    driver = "com.mysql.cj.jdbc.Driver"

    [keystore.tls]
    file_name =  "wso2carbon.jks"
    type =  "JKS"
    password =  "wso2carbon"
    alias =  "wso2carbon"
    key_password =  "wso2carbon"

    [security_audit]
    api_token="6dcffa4c-7004-4f3c-90be-dda3b03acbb2"
    collection_id="5e1b11df-fe32-41a2-a09d-58470f18622d"
    global=true

    [[apim.gateway.environment]]
    name = "Default"
    type = "hybrid"
    display_in_api_console = true
    description = "This is a hybrid gateway that handles both production and sandbox token traffic."
    show_as_token_endpoint_url = true
    service_url = "https://localhost:${mgt.transport.https.port}/services/"
    username= "${admin.username}"
    password= "${admin.password}"
    ws_endpoint = "ws://localhost:9099"
    wss_endpoint = "wss://localhost:8099"
    http_endpoint = "http://gateway.am.wso2.com"
    https_endpoint = "https://gateway.am.wso2.com"
    websub_event_receiver_http_endpoint = "http://websub.am.wso2.com"
    websub_event_receiver_https_endpoint = "https://websub.am.wso2.com"

    [[apim.gateway.environment]]
    name = "Micro-Gateway"
    type = "hybrid"
    display_in_api_console = true
    description = "Choreo Connect micro-gateway."
    show_as_token_endpoint_url = true
    service_url = "https://localhost:${mgt.transport.https.port}/services/"
    username= "${admin.username}"
    password= "${admin.password}"
    ws_endpoint = "http://mgw.wso2.com"
    wss_endpoint = "http://mgw.wso2.com"
    http_endpoint = "http://mgw.wso2.com"
    https_endpoint = "https://mgw.wso2.com"
    websub_event_receiver_http_endpoint = "http://localhost:9021"
    websub_event_receiver_https_endpoint = "https://localhost:8021"

    [apim.sync_runtime_artifacts.gateway]
    gateway_labels =["Default"]

    [apim.analytics]
    enable = true
    config_endpoint = "https://analytics-event-auth.choreo.dev/auth/v1"
    auth_token = "d0986eba-3440-4d90-8ec4-1e0d12bb1a79"

    [apim.devportal]
    url = "https://am.wso2.com/devportal"

    [apim.cors]
    allow_origins = "*"
    allow_methods = ["GET","PUT","POST","DELETE","PATCH","OPTIONS"]
    allow_headers = ["authorization","Access-Control-Allow-Origin","Content-Type","SOAPAction","apikey","Internal-Key"]
    allow_credentials = false

    [[event_handler]]
    name="userPostSelfRegistration"
    subscriptions=["POST_ADD_USER"]

    [service_provider]
    sp_name_regex = "^[\\sa-zA-Z0-9._-]*$"

    [[event_listener]]
    id = "token_revocation"
    type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
    name = "org.wso2.is.notification.ApimOauthEventInterceptor"
    order = 1
    [event_listener.properties]
    notification_endpoint = "https://localhost:${mgt.transport.https.port}/internal/data/v1/notify"
    username = "${admin.username}"
    password = "${admin.password}"
    'header.X-WSO2-KEY-MANAGER' = "default"

    [transport.https.properties]
    proxyPort = 443

    [transport.passthru_https.sender.parameters]
    HostnameVerifier = "AllowAll"

    [database.local]
    url = "jdbc:h2:./repository/database/WSO2CARBON_DB;DB_CLOSE_ON_EXIT=FALSE"

    [apim.monetization]
    monetization_impl = "org.wso2.apim.monetization.impl.StripeMonetizationImpl"
    analytics_query_api_endpoint= "https://analytics-api.choreo.dev/query-api"
    analytics_access_token = "d0986eba-3440-4d90-8ec4-1e0d12bb1a79"

    [[apim.monetization.additional_attributes]]
    name = "ConnectedAccountKey"
    display_name = "ConnectedAccountKey"
    required = "true"
    description = "connected account of the publisher"

    [apim.throttling]
    username = "admin@gogo.com@carbon.super"

    [apim.throttling.jms]
    username = "admin!gogo.com!carbon.super"

    [apim.throttling.policy_deploy]
    username = "$ref{super_admin.username}@carbon.super"

    [[apim.throttling.url_group]]
    traffic_manager_urls = ["tcp://localhost:9611"]
    traffic_manager_auth_urls = ["ssl://localhost:9711"]
    type = "loadbalance"

    [apim.workflow]
    enable = true
    service_url = "https://wso2bps-service:9445/bpmn"
    username = "admin"
    password = "admin"
    callback_endpoint = "http://wso2am-pattern-1-am-service:9763/api/am/admin/v2/workflows/update-workflow-status"
    token_endpoint = "http://wso2am-pattern-1-am-service:9763/oauth2/token"
    client_registration_endpoint = "http://wso2am-pattern-1-am-service:9763/client-registration/v0.17/register"
    client_registration_username = "$ref{super_admin.username}"
    client_registration_password = "$ref{super_admin.password}"

    [apim.opa_security]
    operation_mode = "sync"
    server_endpoint = "http://opa-runtime-service:8181/v1/data"   
kind: ConfigMap
metadata:
  name: wso2am-pattern-1-am-1-conf
  namespace: apim-demo