apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: apim4
    meta.helm.sh/release-namespace: apim-demo
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  creationTimestamp: "2021-05-31T21:54:22Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: wso2am-pattern-1-am-websub-ingress
  namespace: apim-demo
  resourceVersion: "65798341"
  uid: b73c7d6e-f05a-43aa-a282-b29c37359bca
spec:
  rules:
  - host: websub.am.wso2.com
    http:
      paths:
      - backend:
          service:
            name: wso2am-pattern-1-am-service
            port:
              number: 8021
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - websub.am.wso2.com
status:
  loadBalancer:
    ingress:
    - ip: 34.123.88.118
